### ISSUE TITLE
Quick question ref. suitability of your git-sync solution

### ISSUE THREAD

**Issue by Analect** [jayprakashji/git-sync-sidecar#1]
@jayprakashji 
I've hit a wall with the official `kubernets/git-sync`, as per this [issue](https://github.com/kubernetes/git-sync/issues/40#issuecomment-287762179).

Specifically, I'm after a solution that doesn't just emphasise pulling the latest source code and repeating that process.  Instead I'm after a pull once (can set long delay on re-pulls) and then be able to interact with a remote repo using SSH.

I realise your implementation is more PHP centric (symfony and compose), but do you think it might work for my use-case.  I do see some symlinking going on in the git-sync bash script, but I can't judge if this is doing the same thing the [main.go](https://github.com/kubernetes/git-sync/blob/master/cmd/git-sync/main.go) implementation does.

Thanks.

**Comment by jayprakashji** [comment]
My work is heavily inspired by [main.go](https://github.com/kubernetes/git-sync/blob/master/cmd/git-sync/main.go) , it will be in the docs later. PHP stuff completely optional.

What do you mean by " interact with a remote repo using SSH."

something like :
ssh [git-sync-sidecar-ip:port] pull ?


The bash script can work on any base image with bash.
And adding an option to pull once is trivial.

But i don't realy understand, what you want next.

**Comment by Analect** [comment]
Thanks @jayprakashji 
As per this issue [comment](https://github.com/kubernetes/git-sync/issues/40#issuecomment-287762179) back on the original git-sync repo, their symlinking ends up obscuring the folder of the cloned repo ... so as per that comment ... running a `git status` from the cloned repo folder that has been shared via a volume, it tries to delete all files and recreate them in a sub-folder in a hierarchy below ... something I was trying to avoid ... hence I was trying to determine if I might find the same obstacle with this implementation.

**Comment by jayprakashji** [comment]
If I understand you correctly, than yes. The core idea is the same. But...

I need to containerize heavier apps than symfony, some old custom frameworks, where I must use classic pull method instead of new worktree.

'new worktree' method :
- make new worktree
- initialize new worktree
- do custom scripts
- replace symlink

'pull' method :
- git fetch, git pull/merge (in running dir)
- check
- do custom scripts


is that what you need ?

**Comment by Analect** [comment]
@jayprakashji 
Thanks. I appreciate your response. I wasn't really aware of the different approaches, other than the fact that the 'new worktree' one, which I think is what the kubernetes/git-sync uses, plays havoc with what I'm trying to do ... which is simply to clone a repository automatically once ... and then have access to the remote repo for interacting with ... mainly for pushing changes back to the remote, while that pod (containers) are active.

**Comment by jayprakashji** [comment]
well than you don't need anything so complicated as this repo.
Just copy the necessary stuff (ssh key, dirs, git commands) to your own repo and you are done.

**Comment by Analect** [comment]
Thanks @jayprakashji
